
  name: JJKCursedTools
  main: me.axebanz.jJK.JJKCursedToolsPlugin
  version: 1.0
  api-version: "1.21"
  depend: [ModelEngine]

  commands:
    jjk:
      description: "Main JJK command"
      usage: "/jjk"

    wheel:
      description: "Divine Wheel commands"
      usage: "/wheel"

    creation:
      description: "Creation technique commands"
      usage: "/creation"

    cursedspeach:
      description: "Use Cursed Speech abilities (only works if you have the technique)"
      aliases: [cs]
      usage: "/cursedspeach <nomove|plummet|explode>"

    boogiewoogie:
      description: "Use Boogie Woogie abilities (only works if you have the technique)"
      aliases: [bw]
      usage: "/boogiewoogie <clap|swap|clear>"

    copy:
      description: "Use Copy technique abilities (requires bonding with Yuta's Ring)"
      usage: "/copy <summon|dismiss|beam|storage|ct>"

    projection:
      description: "Use Projection Sorcery abilities"
      aliases: [proj]
      usage: "/projection <dash|cancel|status>"

    domain:
      description: "Domain Expansion commands"
      usage: "/domain <expand|collapse|status>"

    idg:
      description: "Idle Death Gamble (Hakari's Domain)"
      usage: "/idg <expand|spin|status>"

    seance:
      description: "Séance technique commands"
      usage: "/seance <activate|status|cancel>"

    strawdoll:
      description: "Straw Doll Technique commands"
      aliases: [sd]
      usage: "/strawdoll <resonance|hairpin|status>"

    tenshadows:
      description: "Ten Shadows Technique commands"
      aliases: [ts]
      usage: "/tenshadows <summon|dismiss|store|ritual|list|status>"

    limitless:
      description: "Limitless Technique commands"
      aliases: [ll]
      usage: "/limitless <infinity|blue|bluemax|red|redmax|purple|nuke|void|status>"

    deadlysentencing:
      description: "Deadly Sentencing Technique commands"
      aliases: [ds]
      usage: "/deadlysentencing <barrage|slam|domain|status>"

    sixtrait:
      description: "Manage the Six Eyes trait"
      usage: "/sixtrait <give|remove|check> <player>"
