package me.axebanz.jJK;

import net.kyori.adventure.key.Key;
import net.kyori.adventure.text.Component;
import org.bukkit.entity.Player;

/**
 * Glyph-based action bar charge UI for Granite Blast.
 *
 * Uses private Unicode characters mapped to custom bar-frame glyphs rendered
 * via a resource pack font.  NO boss bar is used.
 *
 * ── Resource Pack Setup (required, not generated by this plugin) ──────────────
 * Font definition : assets/mybeam/font/default.json
 *   → maps characters \uE100 – \uE10A to bar_0.png – bar_10.png
 * Textures        : assets/mybeam/textures/bar_0.png … bar_10.png
 *   → each image shows the charge bar at the corresponding fill level
 * Charge visual   : mybeam:granite_charge  (separate item-model for the orb above the player's head)
 * ─────────────────────────────────────────────────────────────────────────────
 */
public final class GlyphChargeBar {

    // Private Unicode code-points assigned to each bar frame in the resource pack font.
    // bar_0 = \uE100 (empty), bar_10 = \uE10A (full).
    private static final char[] BAR_FRAMES = {
        '\uE100', // bar_0  —  0 %
        '\uE101', // bar_1  — 10 %
        '\uE102', // bar_2  — 20 %
        '\uE103', // bar_3  — 30 %
        '\uE104', // bar_4  — 40 %
        '\uE105', // bar_5  — 50 %
        '\uE106', // bar_6  — 60 %
        '\uE107', // bar_7  — 70 %
        '\uE108', // bar_8  — 80 %
        '\uE109', // bar_9  — 90 %
        '\uE10A', // bar_10 — 100 %
    };

    private GlyphChargeBar() {}

    /**
     * Maps a charge percentage (0–100) to a bar frame index (0–10).
     *
     * @param chargePercent current charge from 0 to 100
     * @return frame index clamped to [0, 10]
     */
    public static int getBarFrame(int chargePercent) {
        return Math.min(10, Math.max(0, chargePercent / 10));
    }

    /**
     * Sends a glyph charge bar to the player's action bar.
     * The glyph is rendered using the {@code mybeam:default} font from the resource pack.
     *
     * @param player       the player to show the bar to
     * @param chargePercent current charge from 0 to 100
     */
    @SuppressWarnings("PatternValidation")
    public static void showChargeBar(Player player, int chargePercent) {
        int frameIndex = getBarFrame(chargePercent);
        char frame = BAR_FRAMES[frameIndex];
        Component bar = Component.text(String.valueOf(frame))
                .font(Key.key("mybeam", "default"));
        player.sendActionBar(bar);
    }

    /**
     * Clears the action bar for the player (sends an empty component).
     *
     * @param player the player whose action bar should be cleared
     */
    public static void clearChargeBar(Player player) {
        player.sendActionBar(Component.empty());
    }
}
